### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by BenjaminGao** [keenwon/eazydict#1]
#### 环境信息

- 系统及版本: Mac OSX 12.5
- Node 版本: v8.1.2
- 终端软件及版本: iTerm2 Build 3.0.15
- EazyDict 版本:  最新

#### 问题描述:

![screen shot 2017-09-05 at 9 43 22 pm](https://user-images.githubusercontent.com/16028320/30064087-4a344a42-9283-11e7-9d44-7f2cedc57580.png)

**Comment by keenwon** [comment]
sqlite的问题，重新安装下试试

```
npm uninstall -g eazydict
npm install -g eazydict
```

**Comment by keenwon** [comment]
如果还是有问题，参考：

- https://github.com/keenwon/eazydict#安装 下面的备注
- https://github.com/mapbox/node-sqlite3#installing

**Comment by BenjaminGao** [comment]
好了，确实是 sqlite3 的问题。
​

**Comment by keenwon** [comment]
好了就好。
