### ISSUE TITLE
sequelize deprecated

### ISSUE THREAD

**Issue by luminshi** [keenwon/eazydict#2]
#### 环境信息

- 系统及版本: ubuntu 16.04
- Node 版本: 6.11.4
- 终端软件及版本: gnome terminal, bash
- EazyDict 版本: 1.1.2

#### 问题描述:
没有功能上的问题，每次运行这个程序会出现以下提示（需要更换一个包）：

sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators .nvm/versions/node/v6.11.4/lib/node_modules/eazydict/node_modules/sequelize/lib/sequelize.js:236:13

**Comment by keenwon** [comment]
建议升级下node（你用的nvm很容易升级的），然后重新安装下，应该就好了。
我目前用的 node 8.4.0，没有这个提示
如果还有问题我明天好好查下，6.11.4 应该是支持 `Symbol` 的，具体还要看 sequelize 了。

**Comment by luminshi** [comment]
刚测试了下8.6和8.4，发现都给我类似的提示

sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators .nvm/versions/node/v8.6.0/lib/node_modules/eazydict/node_modules/sequelize/lib/sequelize.js:236:13

**Comment by keenwon** [comment]
升级完 `rm -rf node_modules` 然后重装，这个做了吗？

**Comment by luminshi** [comment]
我是直接用nvm安装8.6和8.4的，这机子之前没有装过node的任何包。

**Comment by keenwon** [comment]
升级完了直接 `npm uninstall -g eazydict` 然后 `npm install -g eazydict`，光升级node是没用的，可能和包有关，所以要重装

**Comment by luminshi** [comment]
恩，我就是这么操作的。但还是给了我那个提示。:(

**Comment by keenwon** [comment]
那我明天再查查

**Comment by luminshi** [comment]
恩，多谢！

**Comment by keenwon** [comment]
@luminshi 
新发布了 1.2.1 版本，你可以试下，应该没有这个问题了

```shell
npm install -g eazydict
```

**Comment by keenwon** [comment]
我测试没有问题了，如果还有什么问题，请提 issue 或者 reopen.
